### PR TITLE
postcss 7

### PR DESCRIPTION
**Pull request by goto-bus-stop**
Most postcss plugins now expect postcss 6. I think a lot of them work in both v5 and v6 though because the changes were quite minimal.

This would be a major bump, for those few plugins that do not yet support v6

### CODE REVIEW

**Comment by emilbayes** [comment]
What stalled this? Was just playing with tailwindcss and can't use their custom postcss plugin properly without `postcss@6`, so I'm willing to put the time down. Is it just the conflicts with master? Just tried the changes with their plugin and it works (but not with the current `sheetify-postcss` on npm)

**Comment by goto-bus-stop** [comment]
nothing, rebased and updated to postcss 7

**Comment by emilbayes** [comment]
Works with what I'm doing 👍

**Review by emilbayes — APPROVED** [review]

**Comment by goto-bus-stop** [comment]
:package: 2.0.0

**Pull request merged**
